project:
  title: "SuproFuit 2023 - demo day"
  type: website
  output-dir: docs

editor: visual

website:
  title: "SuproFuit 2023 - demo day"
  search: false
  sidebar:
    background: "#dae0dd"
    logo: logoSuproFruit.png
    contents:
      - index.qmd
      - section: "The Sprayer"
        contents:
          - controlNozzle.qmd
          - flowrate.qmd
          - log.qmd
      - section: "The BiosprayTech experiment"
        contents:
          - xpDesign.qmd
          - disease.qmd
          - lidar.qmd
  page-footer:
    right: "The 16th SUPROFRUIT Workshop - Demo - September 20, 2023"
    left: "&copy; CC BY-NC-ND"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

lang: en
